version: '3.8'
services:
  nginx:
    # image: nginx:latest
    build: .
    ports:
      - "80:80"
    # volumes:
    #   - ./dist:/usr/share/nginx/html
    #   - ./default.conf:/etc/nginx/conf.d/default.conf
    